---
development:
  DB_FILENAME: workers/infrastructure/database/local/dev.db
  API_HOST: http://localhost:9090

test:
  DB_FILENAME: workers/infrastructure/database/local/test.db
  API_HOST: http://localhost:9090

production:
  API_HOST:  https://indie-land-api.herokuapp.com