---
development:
  DB_FILENAME: workers/infrastructure/database/local/dev.db
  # API_HOST: http://localhost:9090

test:
  DB_FILENAME: workers/infrastructure/database/local/test.db
  # API_HOST: http://localhost:9090

app_test:
  DB_FILENAME: workers/infrastructure/database/local/test.db
  # Application
  # API_HOST: http://localhost:9000

production:
  # API_HOST:  https://indie-land-api.herokuapp.com