---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  API_HOST: https://indie-land-api.herokuapp.com/

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  API_HOST: http://localhost:9090

app_test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  # Application
  API_HOST: http://localhost:9000
  