---
  development:
    AWS_ACCESS_KEY_ID: <?>
    AWS_SECRET_ACCESS_KEY: <?>
    AWS_REGION: <?>
    MSG_QUEUE: <?>
    MSG_QUEUE_URL: <?>
    SESSION_SECRET: <?>
    REDISCLOUD_URL: <?>

  test:
    AWS_ACCESS_KEY_ID: <?>
    AWS_SECRET_ACCESS_KEY: <?>
    AWS_REGION: <?>
    MSG_QUEUE: <?>
    MSG_QUEUE_URL: <?>
    SESSION_SECRET: <?>
    REDISCLOUD_URL: <?>
  
  production:
    AWS_ACCESS_KEY_ID: <?>
    AWS_SECRET_ACCESS_KEY: <?>
    AWS_REGION: <?>
    MSG_QUEUE: <?>
    MSG_QUEUE_URL: <?>
    SESSION_SECRET: <?>
    REDISCLOUD_URL: <?>