---
    development:
      SESSION_SECRET: <some secret>
      REDISCLOUD_URL: <url assigned by Redis provider on Heroku>

    test:
      SESSION_SECRET: <some secret>
      REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
    
    production:
      SESSION_SECRET: <some secret>
      REDISCLOUD_URL: <url assigned by Redis provider on Heroku>